name: boost_env
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- alembic=1.13.1=pyhd8ed1ab_1
- antlr-python-runtime=4.9.3=pyhd8ed1ab_1
- anyio=4.3.0=pyhd8ed1ab_0
- argon2-cffi=23.1.0=pyhd8ed1ab_0
- argon2-cffi-bindings=21.2.0=py312h98912ed_4
- arrow=1.3.0=pyhd8ed1ab_0
- asttokens=2.4.1=pyhd8ed1ab_0
- async-lru=2.0.4=pyhd8ed1ab_0
- attrs=23.2.0=pyh71513ae_0
- aws-c-auth=0.7.16=h79b3bcb_6
- aws-c-cal=0.6.10=hb29e0c7_1
- aws-c-common=0.9.13=hd590300_0
- aws-c-compression=0.2.18=hecc5fa9_1
- aws-c-event-stream=0.4.2=hf9b2f7b_4
- aws-c-http=0.8.1=h5d7533a_5
- aws-c-io=0.14.5=h50678d4_1
- aws-c-mqtt=0.10.2=hf479d2b_4
- aws-c-s3=0.5.1=h4ad9680_7
- aws-c-sdkutils=0.1.15=hecc5fa9_1
- aws-checksums=0.1.18=hecc5fa9_1
- aws-crt-cpp=0.26.2=hce0b5c7_6
- aws-sdk-cpp=1.11.267=h5606698_1
- babel=2.14.0=pyhd8ed1ab_0
- beautifulsoup4=4.12.3=pyha770c72_0
- bleach=6.1.0=pyhd8ed1ab_0
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py312h30efb56_1
- bzip2=1.0.8=hd590300_5
- c-ares=1.27.0=hd590300_0
- ca-certificates=2024.2.2=hbcca054_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- certifi=2024.2.2=pyhd8ed1ab_0
- cffi=1.16.0=py312hf06ca03_0
- cfgv=3.3.1=pyhd8ed1ab_0
- charset-normalizer=3.3.2=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_0
- colorlog=6.8.2=py312h7900ff3_0
- comm=0.2.1=pyhd8ed1ab_0
- contourpy=1.2.0=py312h8572e83_0
- cycler=0.12.1=pyhd8ed1ab_0
- debugpy=1.8.1=py312h30efb56_0
- decorator=5.1.1=pyhd8ed1ab_0
- defusedxml=0.7.1=pyhd8ed1ab_0
- distlib=0.3.8=pyhd8ed1ab_0
- entrypoints=0.4=pyhd8ed1ab_0
- exceptiongroup=1.2.0=pyhd8ed1ab_2
- executing=2.0.1=pyhd8ed1ab_0
- filelock=3.15.4=pyhd8ed1ab_0
- fonttools=4.49.0=py312h98912ed_0
- fqdn=1.5.1=pyhd8ed1ab_0
- freetype=2.12.1=h267a509_2
- gflags=2.2.2=he1b5a44_1004
- glog=0.7.0=hed5481d_0
- greenlet=3.0.3=py312h30efb56_0
- h11=0.14.0=pyhd8ed1ab_0
- h2=4.1.0=pyhd8ed1ab_0
- hpack=4.0.0=pyh9f0ad1d_0
- httpcore=1.0.4=pyhd8ed1ab_0
- httpx=0.27.0=pyhd8ed1ab_0
- hydra-core=1.3.2=pyhd8ed1ab_0
- hyperframe=6.0.1=pyhd8ed1ab_0
- icu=73.2=h59595ed_0
- identify=2.6.0=pyhd8ed1ab_0
- idna=3.6=pyhd8ed1ab_0
- importlib-metadata=7.0.1=pyha770c72_0
- importlib_metadata=7.0.1=hd8ed1ab_0
- importlib_resources=6.1.2=pyhd8ed1ab_0
- ipykernel=6.29.3=pyhd33586a_0
- ipython=8.22.1=pyh707e725_0
- isoduration=20.11.0=pyhd8ed1ab_0
- jedi=0.19.1=pyhd8ed1ab_0
- jinja2=3.1.3=pyhd8ed1ab_0
- joblib=1.3.2=pyhd8ed1ab_0
- json5=0.9.17=pyhd8ed1ab_0
- jsonpointer=2.4=py312h7900ff3_3
- jsonschema=4.21.1=pyhd8ed1ab_0
- jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
- jsonschema-with-format-nongpl=4.21.1=pyhd8ed1ab_0
- jupyter-lsp=2.2.3=pyhd8ed1ab_0
- jupyter_client=8.6.0=pyhd8ed1ab_0
- jupyter_core=5.7.1=py312h7900ff3_0
- jupyter_events=0.9.0=pyhd8ed1ab_0
- jupyter_server=2.12.5=pyhd8ed1ab_0
- jupyter_server_terminals=0.5.2=pyhd8ed1ab_0
- jupyterlab=4.1.2=pyhd8ed1ab_0
- jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
- jupyterlab_server=2.25.3=pyhd8ed1ab_0
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.5=py312h8572e83_1
- krb5=1.21.2=h659d440_0
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.40=h41732ed_0
- lerc=4.0.0=h27087fc_0
- libabseil=20240116.1=cxx17_h59595ed_2
- libarrow=15.0.0=h5001e6d_7_cpu
- libarrow-acero=15.0.0=h59595ed_7_cpu
- libarrow-dataset=15.0.0=h59595ed_7_cpu
- libarrow-flight=15.0.0=hf334d8d_7_cpu
- libarrow-flight-sql=15.0.0=h469e5c9_7_cpu
- libarrow-gandiva=15.0.0=h3f306ff_7_cpu
- libarrow-substrait=15.0.0=h469e5c9_7_cpu
- libblas=3.9.0=21_linux64_openblas
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcblas=3.9.0=21_linux64_openblas
- libcrc32c=1.1.2=h9c3ff4c_0
- libcurl=8.5.0=hca28451_0
- libdeflate=1.19=hd590300_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.5.0=hcb278e6_1
- libffi=3.4.2=h7f98852_5
- libgcc-ng=13.2.0=h807b86a_5
- libgfortran-ng=13.2.0=h69a702a_5
- libgfortran5=13.2.0=ha4646dd_5
- libgomp=13.2.0=h807b86a_5
- libgoogle-cloud=2.21.0=h72bcb37_2
- libgoogle-cloud-storage=2.21.0=hc7a4891_2
- libgrpc=1.61.1=h42401df_1
- libiconv=1.17=hd590300_2
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=21_linux64_openblas
- libllvm16=16.0.6=hb3ce162_3
- libnghttp2=1.58.0=h47da74e_1
- libnl=3.9.0=hd590300_0
- libnsl=2.0.1=hd590300_0
- libnuma=2.0.16=h0b41bf4_1
- libopenblas=0.3.26=pthreads_h413a1c8_0
- libparquet=15.0.0=h352af49_7_cpu
- libpng=1.6.43=h2797004_0
- libprotobuf=4.25.2=h08a7969_1
- libre2-11=2023.09.01=h5a48ba9_2
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.45.1=h2797004_0
- libssh2=1.11.0=h0841786_0
- libstdcxx-ng=13.2.0=h7e041cc_5
- libthrift=0.19.0=hb90f79a_1
- libtiff=4.6.0=ha9c0a0a_2
- libutf8proc=2.8.0=h166bdaf_0
- libuuid=2.38.1=h0b41bf4_0
- libwebp-base=1.3.2=hd590300_0
- libxcb=1.15=h0b41bf4_0
- libxcrypt=4.4.36=hd590300_1
- libxml2=2.12.5=h232c23b_0
- libzlib=1.2.13=hd590300_5
- lightgbm=4.3.0=py312h30efb56_0
- lz4-c=1.9.4=hcb278e6_0
- mako=1.3.2=pyhd8ed1ab_0
- markdown-it-py=3.0.0=pyhd8ed1ab_0
- markupsafe=2.1.5=py312h98912ed_0
- matplotlib-base=3.8.3=py312he5832f3_0
- matplotlib-inline=0.1.6=pyhd8ed1ab_0
- mdurl=0.1.2=pyhd8ed1ab_0
- mistune=3.0.2=pyhd8ed1ab_0
- munkres=1.1.4=pyh9f0ad1d_0
- nbclient=0.8.0=pyhd8ed1ab_0
- nbconvert-core=7.16.1=pyhd8ed1ab_0
- nbformat=5.9.2=pyhd8ed1ab_0
- ncurses=6.4=h59595ed_2
- nest-asyncio=1.6.0=pyhd8ed1ab_0
- nodeenv=1.9.1=pyhd8ed1ab_0
- notebook=7.1.1=pyhd8ed1ab_0
- notebook-shim=0.2.4=pyhd8ed1ab_0
- numpy=1.26.4=py312heda63a1_0
- omegaconf=2.3.0=pyhd8ed1ab_0
- openjpeg=2.5.2=h488ebb8_0
- openssl=3.2.1=hd590300_0
- optuna=3.5.0=pyhd8ed1ab_0
- orc=1.9.2=h00e871a_2
- overrides=7.7.0=pyhd8ed1ab_0
- packaging=23.2=pyhd8ed1ab_0
- pandas=2.2.1=py312hfb8ada1_0
- pandocfilters=1.5.0=pyhd8ed1ab_0
- parso=0.8.3=pyhd8ed1ab_0
- patsy=0.5.6=pyhd8ed1ab_0
- pexpect=4.9.0=pyhd8ed1ab_0
- pickleshare=0.7.5=py_1003
- pillow=10.2.0=py312hf3581a9_0
- pip=24.0=pyhd8ed1ab_0
- pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
- platformdirs=4.2.0=pyhd8ed1ab_0
- plotly=5.22.0=pyhd8ed1ab_0
- polars=0.20.11=py312hfa2e56e_0
- pre-commit=3.8.0=pyha770c72_0
- pre_commit=3.8.0=hd8ed1ab_0
- prometheus_client=0.20.0=pyhd8ed1ab_0
- prompt-toolkit=3.0.42=pyha770c72_0
- psutil=5.9.8=py312h98912ed_0
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pure_eval=0.2.2=pyhd8ed1ab_0
- pyarrow=15.0.0=py312h176e3d2_7_cpu
- pycparser=2.21=pyhd8ed1ab_0
- pygments=2.17.2=pyhd8ed1ab_0
- pyparsing=3.1.1=pyhd8ed1ab_0
- pysocks=1.7.1=pyha2e5f31_6
- python=3.12.2=hab00c5b_0_cpython
- python-dateutil=2.8.2=pyhd8ed1ab_0
- python-dotenv=1.0.1=pyhd8ed1ab_0
- python-fastjsonschema=2.19.1=pyhd8ed1ab_0
- python-json-logger=2.0.7=pyhd8ed1ab_0
- python-tzdata=2024.1=pyhd8ed1ab_0
- python_abi=3.12=4_cp312
- pytz=2024.1=pyhd8ed1ab_0
- pyyaml=6.0.1=py312h98912ed_1
- pyzmq=25.1.2=py312h886d080_0
# - rdma-core=50.0=hd3aeb46_0    # This is throwing some error. Better to install manually if needed
- re2=2023.09.01=h7f4b329_2
- readline=8.2=h8228510_1
- referencing=0.33.0=pyhd8ed1ab_0
- requests=2.31.0=pyhd8ed1ab_0
- rfc3339-validator=0.1.4=pyhd8ed1ab_0
- rfc3986-validator=0.1.1=pyh9f0ad1d_0
- rich=13.7.1=pyhd8ed1ab_0
- rpds-py=0.18.0=py312h4b3b743_0
- s2n=1.4.5=h06160fa_0
- scikit-learn=1.4.1.post1=py312h394d371_0
- scipy=1.12.0=py312heda63a1_2
- seaborn=0.13.2=hd8ed1ab_0
- seaborn-base=0.13.2=pyhd8ed1ab_0
- send2trash=1.8.2=pyh41d4057_0
- setuptools=69.1.1=pyhd8ed1ab_0
- six=1.16.0=pyh6c4a22f_0
- snappy=1.1.10=h9fff704_0
- sniffio=1.3.1=pyhd8ed1ab_0
- soupsieve=2.5=pyhd8ed1ab_1
- sqlalchemy=2.0.27=py312h98912ed_0
- stack_data=0.6.2=pyhd8ed1ab_0
- statsmodels=0.14.1=py312hc7c0aa3_0
- tenacity=8.3.0=pyhd8ed1ab_0
- terminado=0.18.0=pyh0d859eb_0
- threadpoolctl=3.3.0=pyhc1e730c_0
- tinycss2=1.2.1=pyhd8ed1ab_0
- tk=8.6.13=noxft_h4845f30_101
- tomli=2.0.1=pyhd8ed1ab_0
- tornado=6.4=py312h98912ed_0
- tqdm=4.66.2=pyhd8ed1ab_0
- traitlets=5.14.1=pyhd8ed1ab_0
- types-python-dateutil=2.8.19.20240106=pyhd8ed1ab_0
- typing-extensions=4.10.0=hd8ed1ab_0
- typing_extensions=4.10.0=pyha770c72_0
- typing_utils=0.1.0=pyhd8ed1ab_0
- tzdata=2024a=h0c530f3_0
- ucx=1.15.0=h75e419f_3
- ukkonen=1.0.1=py312h8572e83_4
- uri-template=1.3.0=pyhd8ed1ab_0
- urllib3=2.2.1=pyhd8ed1ab_0
- virtualenv=20.26.3=pyhd8ed1ab_0
- wcwidth=0.2.13=pyhd8ed1ab_0
- webcolors=1.13=pyhd8ed1ab_0
- webencodings=0.5.1=pyhd8ed1ab_2
- websocket-client=1.7.0=pyhd8ed1ab_0
- wheel=0.42.0=pyhd8ed1ab_0
- xorg-libxau=1.0.11=hd590300_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xz=5.2.6=h166bdaf_0
- yaml=0.2.5=h7f98852_2
- zeromq=4.3.5=h59595ed_1
- zipp=3.17.0=pyhd8ed1ab_0
- zstd=1.5.5=hfc55251_0
